### ISSUE TITLE
Discussion: How to ensure/evaluate the quality of user simulator?

### ISSUE THREAD

**Issue by Tebmer** [FreedomIntelligence/PlatoLM#1]
Thanks for your opensource and great work! Really inspiring and instereting to train a user simulator.

I would like to kindly discuss **how you ensure the quality of the trained user simulator**. For the system agent, we could use evaluation benchmark like MT-bench to evaluate them. But for the trained user simulator, do you have any idea of how to test their quality? Not just from the final performance of the system agent.

I think the quality of the user simulator is very important in your framework.

**Comment by fjiangAI** [comment]
> Thanks for your opensource and great work! Really inspiring and instereting to train a user simulator.
> 
> I would like to kindly discuss **how you ensure the quality of the trained user simulator**. For the system agent, we could use evaluation benchmark like MT-bench to evaluate them. But for the trained user simulator, do you have any idea of how to test their quality? Not just from the final performance of the system agent.
> 
> I think the quality of the user simulator is very important in your framework.

Thank you very much for your insightful question. The evaluation of the quality of user simulators is very important. In this paper, we mainly use its loss to monitor the quality and measure it through the topic diversity and the Humanlike ratio, etc. (as shown in the question level in Table 7). We also acknowledge that this measurement is not comprehensive enough, and we are currently researching this topic.

**Comment by Tebmer** [comment]
Thanks for your reply! Expect your follow-up work.
